spring.main.web-application-type=NONE
spring.cloud.config.uri=${SPRING_CLOUD_CONFIG_URI}
spring.cloud.config.failFast: true
spring.profiles.active=${SPRING_PROFILES_ACTIVE}
spring.application.name=${SPRING_APPLICATION_NAME}
test: "hello world"